### PR TITLE
falconsandbox: bugfix - use vault_info() instead of get_file_path()

### PR DESCRIPTION
**Pull request by rbariatti**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- The `detonate_file` action was failing due to the fact that an old Vault API was used. It was not successful in retrieving vault file's path based on their `vault_id`.
The following deprecated calls:
```python
[...]
try:
    from phantom.vault import Vault
except:
    import phantom.vault as Vault
[...]
Vault.get_file_path(vault_id)
Vault.get_vault_file(vault_id)
[...]
```
have been replaced with the actual Vault API (https://docs.splunk.com/Documentation/SOARonprem/5.3.1/PlaybookAPI/VaultAPI):
```python
[...]
import phantom.rules as ph_rules
[...]
ph_rules.vault_info(container_id=container_id, vault_id=vault_id)
[...]
```
## What is the current behavior? (OPTIONAL)
- The app currently fails to retrieve path of vault files due to deprecated API usage. The `detonate_file` is therefore failing.

## What is the new behavior? (OPTIONAL)
- Using up to date vault API in order to retrieve vault files' path.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by dgopani-crest** [comment]
Hi @rbariatti, Can you please check  Linting and Static Tests failures and fix those. Please let us know if you have any query in that.

**Comment by rbariatti** [comment]
> Hi @rbariatti, Can you please check Linting and Static Tests failures and fix those. Please let us know if you have any query in that.

Hello @dgopani-crest,
To be totally honest. I have only touch small portion of the code and all the linting and static test failure are not related to my changes. 
I made minor changes, just for the action to work. And I will not have time to review all those errors. 
Can you consider fixing those issues during merge process ?

Thank you for your understanding.

**Comment by dgopani-crest** [comment]
Hello @rbariatti, 
As discussed with our product manager @mattsayar-splunk, we will work on this app and release it with the submitted PR.
Thanks!

**Comment by rbariatti** [comment]
@dgopani-crest, @mattsayar-splunk, what a good news. Thank you very much :)

**Review by dhwanis-crest — COMMENTED** [review]
@pdesai-crest  Can you please add release-notes, fips-compliant, update the year in copyright and add port details in readme file?

**Review by pdesai-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Comment by joshquerinphantom** [comment]
@pdesai-crest the static tests are failing. have you looked at them? It appears the GUIDs are not matching. I don't see anything obvious in the commits, but just to double-check.

**Review by joshquerinphantom — APPROVED** [review]

**Pull request merged**
